# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    env_file: .env
    ports:
      - "${LLM_ENDPOINT_PORT}:11434"
    environment:
      NO_PROXY: ${NO_PROXY}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      host_ip: ${HOST_IP}
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped

networks:
  default:
    driver: bridge
